# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pleer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bpleer.proto\"J\n\x12ProductInfoRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\x05\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"u\n\x0bProductShow\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0cproduct_name\x18\x02 \x03(\t\x12\r\n\x05price\x18\x03 \x03(\t\x12\x0e\n\x06rating\x18\x04 \x03(\t\x12\x12\n\nimage_link\x18\x05 \x03(\t\x12\x11\n\tshop_link\x18\x06 \x03(\t\"5\n\x13ProductInfoResponse\x12\x1e\n\x08products\x18\x01 \x03(\x0b\x32\x0c.ProductShow\"\x1e\n\rSearchRequest\x12\r\n\x05\x65nter\x18\x01 \x01(\t\"!\n\x0eSearchResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2E\n\x08Products\x12\x39\n\x0cShowProducts\x12\x13.ProductInfoRequest\x1a\x14.ProductInfoResponse2<\n\x06Search\x12\x32\n\rSearchProduct\x12\x0e.SearchRequest\x1a\x0f.SearchResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pleer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCTINFOREQUEST._serialized_start=15
  _PRODUCTINFOREQUEST._serialized_end=89
  _PRODUCTSHOW._serialized_start=91
  _PRODUCTSHOW._serialized_end=208
  _PRODUCTINFORESPONSE._serialized_start=210
  _PRODUCTINFORESPONSE._serialized_end=263
  _SEARCHREQUEST._serialized_start=265
  _SEARCHREQUEST._serialized_end=295
  _SEARCHRESPONSE._serialized_start=297
  _SEARCHRESPONSE._serialized_end=330
  _PRODUCTS._serialized_start=332
  _PRODUCTS._serialized_end=401
  _SEARCH._serialized_start=403
  _SEARCH._serialized_end=463
# @@protoc_insertion_point(module_scope)
