# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ya.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ya.proto\"L\n\x14YaProductInfoRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\x05\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"w\n\rYaProductShow\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0cproduct_name\x18\x02 \x03(\t\x12\r\n\x05price\x18\x03 \x03(\t\x12\x0e\n\x06rating\x18\x04 \x03(\t\x12\x12\n\nimage_link\x18\x05 \x03(\t\x12\x11\n\tshop_link\x18\x06 \x03(\t\"9\n\x15YaProductInfoResponse\x12 \n\x08products\x18\x01 \x03(\x0b\x32\x0e.YaProductShow\" \n\x0fYaSearchRequest\x12\r\n\x05\x65nter\x18\x01 \x01(\t\"#\n\x10YaSearchResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2M\n\nYaProducts\x12?\n\x0eYaShowProducts\x12\x15.YaProductInfoRequest\x1a\x16.YaProductInfoResponse2D\n\x08YaSearch\x12\x38\n\x0fYaSearchProduct\x12\x10.YaSearchRequest\x1a\x11.YaSearchResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ya_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _YAPRODUCTINFOREQUEST._serialized_start=12
  _YAPRODUCTINFOREQUEST._serialized_end=88
  _YAPRODUCTSHOW._serialized_start=90
  _YAPRODUCTSHOW._serialized_end=209
  _YAPRODUCTINFORESPONSE._serialized_start=211
  _YAPRODUCTINFORESPONSE._serialized_end=268
  _YASEARCHREQUEST._serialized_start=270
  _YASEARCHREQUEST._serialized_end=302
  _YASEARCHRESPONSE._serialized_start=304
  _YASEARCHRESPONSE._serialized_end=339
  _YAPRODUCTS._serialized_start=341
  _YAPRODUCTS._serialized_end=418
  _YASEARCH._serialized_start=420
  _YASEARCH._serialized_end=488
# @@protoc_insertion_point(module_scope)
